const AdministorData = [
  {
    id: "flush-collapseOne",
    cls: "",
    cls2: "show",
    aria: true,
    title: "Managing Committee",
    desc: "one",
    sr: 1,
    name: "vikas",
    desti: "assistent professor",
    contact: 1234567890,
    email: "xyz@gmail.com",
    sclass: "even",
  },
  {
    id: "flush-collapseTwo",
    cls: "collapsed",
    cls2: "",
    aria: false,
    title: "Proctorial Board",
    desc: "two",
    sr: 1,
    name: "ram",
    desti: "assistent professor",
    contact: 1234567890,
    email: "xyz@gmail.com",
    sclass: "even",
  },
  // {
  //   id: "flush-collapseTwo",
  //   cls: "collapsed",
  //   cls2: "",
  //   aria: false,
  //   title: "Proctorial Board",
  //   desc: `two`,
  //   sr:1,
  //   name:"jai singh",
  //   desti:"assistent professor",
  //   contact:1234567890,
  //   email:"xyz@gmail.com",
  //   sclass:"even"
  // },
  {
    id: "flush-collapseThree",
    cls: "collapsed",
    cls2: "",
    aria: false,
    title: "College Committee",
    desc: `two`,
    sr: 1,
    name: "jai singh",
    desti: "assistent professor",
    contact: 1234567890,
    email: "xyz@gmail.com",
    sclass: "even",
  },
  {
    id: "flush-collapseFour",
    cls: "collapsed",
    cls2: "",
    aria: false,
    title: "Office Staff",
    desc: `two`,
    sr: 1,
    name: "jai singh",
    desti: "assistent professor",
    contact: 1234567890,
    email: "xyz@gmail.com",
    sclass: "even",
  },
];
export default AdministorData;